### ISSUE TITLE
代码出现bug

### ISSUE THREAD

**Issue by Zhao187** [Peakmain/BasicUI#1]
1.ShapeTextView:
 /**
     * 设置背景色 以及线条宽度和颜色
     */
    private void setStroke() {
        //线条
        mGradientDrawable.setStroke(mNormalStrokeWidth, mNormalStrokeColor);
        mGradientDrawable.setCornerRadius(mRadius);
        mGradientDrawable.setColor(mNormalBackgroundColor);
    }

线条颜色有问题
2.希望app能够提供demo

**Comment by Peakmain** [comment]
已经提供demo了，有问题欢迎提出来，谢谢
